{% set version = "20180710" %}
{% set name = "eclib" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/JohnCremona/eclib/archive/v{{ version }}.tar.gz
  sha256: 176840c9dbed6156f291da3c877ce680f746acf0dcd1b952174f1e046f28b71d

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('eclib', max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - libtool
    - automake
  host:
    - pari
    - ntl
    - libflint
    - mpfr
    - gmp
  run:
    - {{ pin_compatible('pari') }}
    - ntl
    - libflint
    - mpfr
    - gmp

test:
  commands:
    - test -f ${PREFIX}/include/eclib/arith.h
    - test -f ${PREFIX}/lib/libec.a
    - test -f ${PREFIX}/lib/libec.dylib     # [osx]
    - test -f ${PREFIX}/lib/libec.so        # [linux]

about:
  home: https://github.com/JohnCremona/eclib
  license: GPLv2
  license_file: COPYING
  summary: |
    The eclib package includes mwrank (for 2-descent on elliptic curves over Q) and
    modular symbol code used to create the elliptic curve database.
  dev_url: https://github.com/JohnCremona/eclib

extra:
  recipe-maintainers:
    - isuruf
