travis:
  secure:
    BINSTAR_TOKEN: scCDLpV3Vf/ulFqtgGb1qlCHGqklM6vju1PTTe8KNcbiLFupo5RMvoLuc29nj+XEk1Wb4+vjVUDElzdH9oz8gByJtob9wmHR8NQmGnOmVSvux6XJACQTKiGh9gHOkQOmuRB1Jz1gTwMZDnZPtka+NSaNRV5lxQXshBW1BP7RLqR9kZO3eJ3QL4GNFyURhYTIPfQa/gwJV/CmO+5Ntn+9x+chuRXoWhl20HcOzr1MsGhzF5nRoXxlusHw25Wno+e6Tfs7QiH4eY029hgjwFL1xLizis8o5ydEysrOLyzYciOF+B2gjwIqrxFl3kzZ81zTOukC5ZD3Z5q4VV/OIgCzHwUhkdLc/9HV0UuVzlhG2J4WdbDGMPi2OLMp1Pbak5AQ1/rL59IZFPQLNfmEBngwkffKsuQNnV2ZR4Xdk0LycTFhTLYRggGbT07qdw7g7i1SWkwj/t8+0mI6HF+RvLV7zF+8ajF9Dg31yoS7YoFOiiPJFDzCRAbNS4ubxwsewEGEOpoBs61kf31SWo8FrHRumsbC+1dpWauId6SoWwa0A+qg4TBfcQitOxAOImsSSbk9nidmz77jxXwBkr3Iuf8sOfx2kYQV/ZM7NAaUy4ZMg+ONe19uB362wPLyadyS9tElAAx9Uy5gL1O1c7IhCVJqHCYcNACLTOThElwTP1M4dik=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
